CREATE TABLE PERSONAS (
	NOMBRE VARCHAR(25),
	APELLIDO VARCHAR(25),
	EDAD INT,
	ESTATURA DECIMAL(3,2) --(CANT DE NUMEROS A TENER, NUMEROS DESPUES DE LA COMA)
)


INSERT INTO PERSONAS VALUES     --CREAMOS VALORES PARA LA TABLA
	('Juan', 'Pérez', 15, 1.75),
    ('María', 'González', 30, 1.60),
    ('Luis', 'Martínez', 35, 1.80),
    ('Ana', 'López', 28, 1.65),
    ('Carlos', 'Rodríguez', 40, 1.70),
    ('Laura', 'Sánchez', 22, 1.55),
    ('Pedro', 'Hernández', 33, 1.75),
    ('Sofía', 'Díaz', 14, 1.70),
    ('Miguel', 'Ruiz', 27, 1.80),
    ('Lucía', 'Torres', 31, 1.60),
	('Myke', 'Towers', 30, 1.76),
    ('Joaquinha', 'Riva', 29, 1.70),
    ('Antonella', 'Pane', 27, 1.75),
    ('Marcelo', 'Toscano', 57, 1.60),
    ('Carlos', 'Maslaton', 31, 1.65);

	SELECT * FROM PERSONAS

	SELECT * FROM PERSONAS WHERE EDAD > 18 -- MOSTRAR TODAS LAS PERSONAS CON MAS DE 18

	SELECT * FROM PERSONAS ORDER BY ESTATURA --Mostrar por estatura

	SELECT * FROM PERSONAS ORDER BY APELLIDO, NOMBRE --Mostrar ordenado por apellido y nombre

	SELECT * FROM PERSONAS WHERE EDAD >= 18 ORDER BY APELLIDO, NOMBRE; --MOSTRAR TODOS LOS MAYORES DE 18 ORDENADO POR NOMBRE Y APELLIDO

	SELECT * FROM PERSONAS WHERE EDAD = 30

	DELETE FROM PERSONAS WHERE EDAD = 30 --ELIMINAR TODOS LOS QUE TENGAN 30

	UPDATE PERSONAS
	SET ESTATURA = ESTATURA - 0.05 -- ACTUALIZA LA ESTATURA 
	WHERE ESTATURA > 1.75 --siempre y cuando sea mayor a 1,75

	SELECT TOP 1 NOMBRE, APELLIDO FROM PERSONAS ORDER BY EDAD -- MUESTRA LA PERSONA MAS JOVEN, EL TOP UNO DE LA LISTA ORDENADA POR EDAD.

	SELECT * FROM PERSONAS WHERE ESTATURA <= 1.60

	DELETE FROM PERSONAS WHERE ESTATURA <= 1.60 --ELIMINAR PERSONAS MENORES A 1,60

	UPDATE PERSONAS
	SET EDAD = EDAD + 2 -- SUMARLE DOS A LA EDAD 
	WHERE EDAD > 20 -- CUANDO LA EDAD SEA MAYOR A 20

	SELECT NOMBRE, APELLIDO, EDAD FROM PERSONAS --MOSTRAR NOMBRE APELLIDO Y EDAD DE LA TABLA
	WHERE EDAD > 25 AND EDAD < 35 --DONDE LA EDAD SEA ENTRE 25 Y 35
	ORDER BY EDAD DESC --ORDENADO DECENDIENTEMENTE

	SELECT * FROM PERSONAS WHERE NOMBRE = 'Juan'

	DELETE FROM PERSONAS WHERE NOMBRE = 'Juan' --eliminar a todos los juan de la lista
